# Reference: https://www.vagrantup.com/docs/provisioning/docker.html

docker_compose_install = <<-SCRIPT
  echo "Installing docker compose v1.25"
  curl -s -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  chmod +x /usr/local/bin/docker-compose
  ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_version = "20191030.0.0"
  config.vm.box_check_update = true

  config.vm.define "dockervm" do |docker_host|
    docker_host.vm.hostname = "dockervm"
    docker_host.vm.network "public_network", bridge: "wlo1"

    docker_host.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = 2_048
      vb.cpus = 2
    end

    # use docker provisioner instead of the shell provisioner
    docker_host.vm.provision "docker"
    docker_host.vm.provision "shell", inline: docker_compose_install
  end

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
end
