version: "3.7"

services:
  drupal:
    image: drupal:latest
    ports:
      - 8090:80
    depends_on:
      - postgresql
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_sites:/var/www/html/sites
      - drupal_themes:/var/www/html/themes

  postgresql:
    image: postgres:10-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: drupal_production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: "pg_isready -d postgres -U postgres"
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_sites:
  drupal_themes:
  pg_data:
